apiVersion: v2
name: open-webui
version: 14.7.0
appVersion: 0.9.5
home: https://github.com/enclaive/garnet-helm
icon: >-
  https://raw.githubusercontent.com/open-webui/open-webui/main/static/favicon.png
description: "Garnet: Privacy-aware AI chat platform built on Open WebUI"
keywords:
  - llm
  - chat
  - web-ui
  - open-webui
  - privacy
  - garnet
sources:
  - https://github.com/enclaive/garnet-helm
  - https://github.com/otwld/ollama-helm/
  - https://hub.docker.com/r/ollama/ollama
annotations:
  licenses: MIT
dependencies:
  - name: ollama
    repository: https://otwld.github.io/ollama-helm/
    version: ">=0.24.0"
    import-values:
      - child: service
        parent: ollama.service
    condition: ollama.enabled
  - name: pipelines
    repository: https://helm.openwebui.com
    version: ">=0.10.1"
    import-values:
      - child: service
        parent: pipelines.service
    condition: pipelines.enabled
