apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "terminals.fullname" . }}-operator
  namespace: {{ include "terminals.namespace" . }}
  labels:
    {{- include "terminals.operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.operator.replicaCount }}
  selector:
    matchLabels:
      {{- include "terminals.operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "terminals.operator.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "terminals.serviceAccountName" . }}
      containers:
        - name: operator
          image: "{{ .Values.operator.image.repository }}:{{ .Values.operator.image.tag }}"
          imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
          {{- with .Values.operator.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
