{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "terminals.secretName" . }}
  namespace: {{ include "terminals.namespace" . }}
  labels:
    {{- include "terminals.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-key: {{ .Values.apiKey | default (randAlphaNum 32) | quote }}
{{- end }}
