apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mcpo.fullname" . }}
  labels:
    {{- include "mcpo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "mcpo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mcpo.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.container.image.repository }}:{{ .Values.container.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.container.image.pullPolicy }}
          command: ["mcpo"]
          args: ["--config", "/config/config.json"]
          volumeMounts:
            - name: config-volume
              mountPath: /config
          resources:
            {{- toYaml .Values.container.resources | nindent 12 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "mcpo.fullname" . }}-config
