{{- if eq .Values.mode "cronjob" }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "oikb.fullname" . }}
  namespace: {{ include "oikb.namespace" . }}
  labels:
    {{- include "oikb.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cronjob.schedule | quote }}
  concurrencyPolicy: {{ .Values.cronjob.concurrencyPolicy }}
  successfulJobsHistoryLimit: {{ .Values.cronjob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cronjob.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "oikb.selectorLabels" . | nindent 12 }}
            {{- with .Values.podLabels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        spec:
          serviceAccountName: {{ include "oikb.serviceAccountName" . }}
          restartPolicy: {{ .Values.cronjob.restartPolicy }}
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.podSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
            - name: oikb
              image: {{ include "oikb.image" . | quote }}
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command: {{ .Values.cronjob.command | toJson }}
              {{- with .Values.cronjob.args }}
              args: {{ . | toJson }}
              {{- end }}
              {{- with .Values.containerSecurityContext }}
              securityContext:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              env:
                {{- include "oikb.containerEnv" . | nindent 16 }}
              volumeMounts:
                {{- include "oikb.configVolumeMount" . | nindent 16 }}
              {{- with .Values.resources }}
              resources:
                {{- toYaml . | nindent 16 }}
              {{- end }}
          volumes:
            {{- include "oikb.configVolume" . | nindent 12 }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
