{{- if or (eq .Values.mode "daemon") .Values.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oikb.envSecretName" . }}
  namespace: {{ include "oikb.namespace" . }}
  labels:
    {{- include "oikb.labels" . | nindent 4 }}
type: Opaque
stringData:
  oikb-api-key: {{ .Values.apiKey | default (randAlphaNum 32) | quote }}
{{- end }}
{{- if and .Values.openWebuiApiKey (not .Values.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oikb.owuiKeySecretName" . }}
  namespace: {{ include "oikb.namespace" . }}
  labels:
    {{- include "oikb.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.existingSecretKey }}: {{ .Values.openWebuiApiKey | quote }}
{{- end }}
