name: Test Pipelines Helm Chart

on:
  pull_request:
    paths:
      - "charts/pipelines/**"
  push:
    branches:
      - main
    paths:
      - "charts/pipelines/**"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Lint pipelines chart
        run: helm lint ./charts/pipelines

  template:
    name: Template render
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Template pipelines chart
        run: helm template pipelines ./charts/pipelines --namespace garnet > /dev/null
